### ISSUE TITLE
Deny to topic all together.

### ISSUE THREAD

**Issue by gkristjansson** [hivemq/hivemq-spi#1]
I have kind of special use case I am trying to use hive to implement a chat server. One of the feature that I want to have is to be able to ban or disallow some users from pub/sub to some rooms/topics.

The problem is I don't see how I can use `OnAuthorizationCallback` and `MqttTopicPermissions` to deny access to a topic all together. 

My think was to have OnAuthorizationCallback return a list of MqttTopicPermissions
with the first entry saying /chat/BanFromRoom and DENY ALL and
another entry saying /chat/+ ALLOW pub and sub.

Is my think way of track here.

**Comment by dobermai** [comment]
HiveMQ 2.x only has a whitelist concept, so you need to define your allowed topics. I see that this is not optimal in your case.

The good news is, the DENY and ALLOW concept is implemented in the upcoming HiveMQ 3.0 which will be released end of September. If you want early access to that version (including early access SPI access), please let us know by writing to support@hivemq.com.

**Comment by dobermai** [comment]
A Blacklist and Whitelist example for HiveMQ 3 is available here: https://github.com/hivemq/hivemq-authorization-blacklist-whitelist-example

I'm closing this issue, feel free to reopen if this won't work for you.
