### ISSUE TITLE
Last Will of authenticated client affected by permissions for anonymous clients

### ISSUE THREAD

**Issue by MatthiasMolitor** [hivemq/hivemq-spi#4]
We developed an authentication/authorization plugin for HiveMQ.
In our authorization callback, we do not grant any permissions if the client is not marked as *authenticated*:

    public class MyAuthorizationCallback implements OnAuthorizationCallback {

        @Override
        public List<MqttTopicPermission> getPermissionsForClient(final ClientData clientData) {
            if (!clientData.isAuthenticated()) {
                return Collections.emptyList();
            }
            // [...]
        }

        // [...]
    }

We noticed that a client that is *not* marked as authenticated (although valid credentials were provided) is passed to the authorization callback if a Last Will is provided on connect.
As shown above, we do not grant any permissions in that case and the client connection is rejected.
If we grant the permissions regardless of the authentication status, then the connection is accepted.

We reproduced that behavior with a plugin based on `hivemq-spi` in version `3.3.0` and HiveMQ brokers in the versions `3.2.8` and `3.3.1`.

We checked the [HiveMQ Plugin Developer Guide](https://www.hivemq.com/docs/plugins/latest/), but did not find information regarding that special case.

We would have expected an *authenticated* client whose permissions for the Last Will topic are checked.

Are we using the plugin API in a wrong way or is this a bug? 
If it's not a bug, then additional documentation might help.

We are happy to provide additional information if that helps to clarify this case.

**Comment by crmolinaz** [comment]
The Authentication of clients with LWT can’t be completed until the OnAuthorizationCallback was called. 
The reason for that is that the LWT can’t be checked without the permissions that are set on the OnAuthorizationCallback.

For that reason, the “isAuthenticated()” method cannot be used as a qualifier for clients connecting with a LWT.

**Comment by MatthiasMolitor** [comment]
For documentation purposes: `LWT` = Last Will Topic

The HiveMQ documentation has been updated. This is the relevant part: [Authorization Callback Documentation](https://www.hivemq.com/docs/plugins/latest/#onAuthorization-callback)

**Comment by dobermai** [comment]
I guess this issue can be closed now? Feel free to reopen the issue in case this isn't resolved now.
