### ISSUE TITLE
SubscriptionStore's getSubscribers doesn't return all topics in case passed topic contains multi-level wildcard

### ISSUE THREAD

**Issue by frankyfish** [hivemq/hivemq-spi#7]
Hello HiveMQ team.

I am developing a HiveMQ plugin which makes use of `RESTService` and `HttpListener`. Plugin accepts topic or list of topics as a JSON and returns a _clientId_ (or list of clientIds) of client(-s) subscribed to passed topics.
Here's a link to the code in demo repo: https://github.com/frankyfish/hivemq-sub-plugin-demo/blob/master/src/main/java/org/example/resources/SubscriptionResource.java#L34

I am a bit confused on how does `BlockingSubscriptionStore::getSubscribers` works.
For example there are two clients with client IDs: ClientA & ClientB
ClientA subscribed on `test/sub/topic` (QoS 1)
ClientB subscribed on `test/#` (QoS 1)
Whenever I ask my plugin to get me subscribers of `test/#` only ClientB is returned. Documentation of `getSubscribers` method states following:

`Returns all MQTT client subscriber identifiers for a given topic, this HiveMQ instance and all other nodes in a HiveMQ cluster. MQTT Wildcards are allowed.`

With following description I would expect request for `test/#` to return **_both_** ClientA & ClientB which is obviously not the case here.
![image](https://user-images.githubusercontent.com/25501399/111811579-3fda6680-88e8-11eb-8ffe-645b67e5d332.png)
However whenever I request subscribers of `test/sub/topic` both ClientA & ClientB client IDs are returned:
![image](https://user-images.githubusercontent.com/25501399/111811230-e6723780-88e7-11eb-9c45-2584cd96e5b2.png)
This makes me to think that multi-level wildcard passed to `getSubscribers` topic is ignored in terms of logic behind it and rather used as a simple string for matching. So my questions would be:
1. Is this an expected behaviour?
2. Is there a way to get the list of client IDs of clients subscribed to topic that contains certain string? 
Or some sort if multi-level wildcard for selecting clients subscribed to topic matching certain pattern. Like, for example, passing `test/#` to `getSubscribers` would return clients subscribed to `test/sub/topic`, `test/sub/topic1`.
I really don't want to proceed with search of matching topics by iterating via the list of all clients because with hundreds of thousands of clients this might end up hitting performance badly.

I am using HiveMQ 3.4.7 in the example repo, behaviour is the same for v3.4.6 (unfortunately I am limited to versions <4).
HiveMQ SPI v. 3.4.4.

You can easily reproduce behaviour above by checking out repo: https://github.com/frankyfish/hivemq-sub-plugin-demo
There is a Dockerfile that setups everything.

Not sure that I've correctly chosen the project for current issue if it is the case - sorry for that. I can re-create it wherever you tell it belongs to.
Thanks in advance!

**Comment by fraschbi** [comment]
Hi @frankyfish,

Nice to see your interest in HiveMQ and your efforts to write your own plugin.
Please open a thread on the [HiveMQ Community Forum](https://community.hivemq.com/) to get assistance.

Thank you,
Florian

**Comment by frankyfish** [comment]
Created thread:  https://community.hivemq.com/t/efficient-way-to-collect-client-ids-of-clients-subscribed-on-a-topic/472
